// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// addonsDictTypeDao is the data access object for the table addons_dict_type.
// You can define custom methods on it to extend its functionality as needed.
type addonsDictTypeDao struct {
	*internal.AddonsDictTypeDao
}

var (
	// AddonsDictType is a globally accessible object for table addons_dict_type operations.
	AddonsDictType = addonsDictTypeDao{internal.NewAddonsDictTypeDao()}
)

// Add your custom methods and functionality below.
