// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// addonsDictInfoDao is the data access object for the table addons_dict_info.
// You can define custom methods on it to extend its functionality as needed.
type addonsDictInfoDao struct {
	*internal.AddonsDictInfoDao
}

var (
	// AddonsDictInfo is a globally accessible object for table addons_dict_info operations.
	AddonsDictInfo = addonsDictInfoDao{internal.NewAddonsDictInfoDao()}
)

// Add your custom methods and functionality below.
