// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// baseSysInitDao is the data access object for the table base_sys_init.
// You can define custom methods on it to extend its functionality as needed.
type baseSysInitDao struct {
	*internal.BaseSysInitDao
}

var (
	// BaseSysInit is a globally accessible object for table base_sys_init operations.
	BaseSysInit = baseSysInitDao{internal.NewBaseSysInitDao()}
)

// Add your custom methods and functionality below.
