// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// baseSysAnnouncementDao is the data access object for the table base_sys_announcement.
// You can define custom methods on it to extend its functionality as needed.
type baseSysAnnouncementDao struct {
	*internal.BaseSysAnnouncementDao
}

var (
	// BaseSysAnnouncement is a globally accessible object for table base_sys_announcement operations.
	BaseSysAnnouncement = baseSysAnnouncementDao{internal.NewBaseSysAnnouncementDao()}
)

// Add your custom methods and functionality below.
