// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// baseEpsAppDao is the data access object for the table base_eps_app.
// You can define custom methods on it to extend its functionality as needed.
type baseEpsAppDao struct {
	*internal.BaseEpsAppDao
}

var (
	// BaseEpsApp is a globally accessible object for table base_eps_app operations.
	BaseEpsApp = baseEpsAppDao{internal.NewBaseEpsAppDao()}
)

// Add your custom methods and functionality below.
