// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// baseEpsAdminDao is the data access object for the table base_eps_admin.
// You can define custom methods on it to extend its functionality as needed.
type baseEpsAdminDao struct {
	*internal.BaseEpsAdminDao
}

var (
	// BaseEpsAdmin is a globally accessible object for table base_eps_admin operations.
	BaseEpsAdmin = baseEpsAdminDao{internal.NewBaseEpsAdminDao()}
)

// Add your custom methods and functionality below.
