// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// baseSysAnnouncementReadDao is the data access object for the table base_sys_announcement_read.
type baseSysAnnouncementReadDao struct {
	*internal.BaseSysAnnouncementReadDao
}

var (
	// BaseSysAnnouncementRead is a globally accessible object for table base_sys_announcement_read operations.
	BaseSysAnnouncementRead = baseSysAnnouncementReadDao{internal.NewBaseSysAnnouncementReadDao()}
)
