// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// baseSysSettingDao is the data access object for the table base_sys_setting.
// You can define custom methods on it to extend its functionality as needed.
type baseSysSettingDao struct {
	*internal.BaseSysSettingDao
}

var (
	// BaseSysSetting is a globally accessible object for table base_sys_setting operations.
	BaseSysSetting = baseSysSettingDao{internal.NewBaseSysSettingDao()}
)

// Add your custom methods and functionality below.
