// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// baseSysAddonsDao is the data access object for the table base_sys_addons.
// You can define custom methods on it to extend its functionality as needed.
type baseSysAddonsDao struct {
	*internal.BaseSysAddonsDao
}

var (
	// BaseSysAddons is a globally accessible object for table base_sys_addons operations.
	BaseSysAddons = baseSysAddonsDao{internal.NewBaseSysAddonsDao()}
)

// Add your custom methods and functionality below.
