// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// baseSysQuickMenuDao is the data access object for the table base_sys_quick_menu.
// You can define custom methods on it to extend its functionality as needed.
type baseSysQuickMenuDao struct {
	*internal.BaseSysQuickMenuDao
}

var (
	// BaseSysQuickMenu is a globally accessible object for table base_sys_quick_menu operations.
	BaseSysQuickMenu = baseSysQuickMenuDao{internal.NewBaseSysQuickMenuDao()}
)

// Add your custom methods and functionality below.
