// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// baseSysAddonsTypesDao is the data access object for the table base_sys_addons_types.
// You can define custom methods on it to extend its functionality as needed.
type baseSysAddonsTypesDao struct {
	*internal.BaseSysAddonsTypesDao
}

var (
	// BaseSysAddonsTypes is a globally accessible object for table base_sys_addons_types operations.
	BaseSysAddonsTypes = baseSysAddonsTypesDao{internal.NewBaseSysAddonsTypesDao()}
)

// Add your custom methods and functionality below.
