// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// baseSysActionLogDao is the data access object for the table base_sys_action_log.
// You can define custom methods on it to extend its functionality as needed.
type baseSysActionLogDao struct {
	*internal.BaseSysActionLogDao
}

var (
	// BaseSysActionLog is a globally accessible object for table base_sys_action_log operations.
	BaseSysActionLog = baseSysActionLogDao{internal.NewBaseSysActionLogDao()}
)

// Add your custom methods and functionality below.
