// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// baseSysNoticeUserReadDao is the data access object for the table base_sys_notice_user_read.
// You can define custom methods on it to extend its functionality as needed.
type baseSysNoticeUserReadDao struct {
	*internal.BaseSysNoticeUserReadDao
}

var (
	// BaseSysNoticeUserRead is a globally accessible object for table base_sys_notice_user_read operations.
	BaseSysNoticeUserRead = baseSysNoticeUserReadDao{internal.NewBaseSysNoticeUserReadDao()}
)

// Add your custom methods and functionality below.
