// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// baseSysFeedbackDao is the data access object for the table base_sys_feedback.
// You can define custom methods on it to extend its functionality as needed.
type baseSysFeedbackDao struct {
	*internal.BaseSysFeedbackDao
}

var (
	// BaseSysFeedback is a globally accessible object for table base_sys_feedback operations.
	BaseSysFeedback = baseSysFeedbackDao{internal.NewBaseSysFeedbackDao()}
)

// Add your custom methods and functionality below.
