// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"dzhgo/internal/dao/internal"
)

// baseSysNoticeDao is the data access object for the table base_sys_notice.
// You can define custom methods on it to extend its functionality as needed.
type baseSysNoticeDao struct {
	*internal.BaseSysNoticeDao
}

var (
	// BaseSysNotice is a globally accessible object for table base_sys_notice operations.
	BaseSysNotice = baseSysNoticeDao{internal.NewBaseSysNoticeDao()}
)

// Add your custom methods and functionality below.
