// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/addons/member/dao/internal"
)

// internalAddonsMemberAttrDao is internal type for wrapping internal DAO implements.
type internalAddonsMemberAttrDao = *internal.AddonsMemberAttrDao

// addonsMemberAttrDao is the data access object for table addons_member_attr.
// You can define custom methods on it to extend its functionality as you wish.
type addonsMemberAttrDao struct {
	internalAddonsMemberAttrDao
}

var (
	// AddonsMemberAttr is globally public accessible object for table addons_member_attr operations.
	AddonsMemberAttr = addonsMemberAttrDao{
		internal.NewAddonsMemberAttrDao(),
	}
)

// Fill with you ideas below.
