// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"dzhgo/addons/member/dao/internal"
)

// internalAddonsMemberManageDao is internal type for wrapping internal DAO implements.
type internalAddonsMemberManageDao = *internal.AddonsMemberManageDao

// addonsMemberManageDao is the data access object for table addons_member_manage.
// You can define custom methods on it to extend its functionality as you wish.
type addonsMemberManageDao struct {
	internalAddonsMemberManageDao
}

var (
	// AddonsMemberManage is globally public accessible object for table addons_member_manage operations.
	AddonsMemberManage = addonsMemberManageDao{
		internal.NewAddonsMemberManageDao(),
	}
)

// Fill with you ideas below.
